const companies = [
  {
    name: "Apple Inc",
    id: 10000001,
    products: ["iPhone", "iPad", "MacBook"],
    businessScope: ["国际", "国内"],
    location: "Cupertino",
  },
  {
    name: "Amazon.com Inc",
    id: 10000002,
    products: ["Amazon Echo", "Kindle", "Prime Video"],
    businessScope: ["国际"],
    location: "Seattle",
  },
  {
    name: "Microsoft Corporation",
    id: 10000003,
    products: ["Windows", "Surface", "Xbox"],
    businessScope: ["国际", "国内"],
    location: "Redmond",
  },
  {
    name: "Alphabet Inc",
    id: 10000004,
    products: ["Google Search", "YouTube", "Android"],
    businessScope: ["国际"],
    location: "Mountain View",
  },
  {
    name: "Facebook, Inc",
    id: 10000005,
    products: ["Facebook", "Instagram", "WhatsApp"],
    businessScope: ["国际"],
    location: "Menlo Park",
  },
  {
    name: "Tesla, Inc",
    id: 10000006,
    products: ["Model S", "Model 3", "Model X"],
    businessScope: ["国际"],
    location: "Palo Alto",
  },
  {
    name: "Walmart Inc",
    id: 10000007,
    products: ["Groceries", "Electronics", "Clothing"],
    businessScope: ["国内"],
    location: "Bentonville",
  },
  {
    name: "Tencent Holdings Limited",
    id: 10000008,
    products: ["WeChat", "Tencent QQ", "Honor of Kings"],
    businessScope: ["国际", "国内"],
    location: "Shenzhen",
  },
  {
    name: "Alibaba Group Holding Limited",
    id: 10000009,
    products: ["Alibaba.com", "Taobao", "Tmall"],
    businessScope: ["国际", "国内"],
    location: "Hangzhou",
  },
  {
    name: "Samsung Electronics Co., Ltd",
    id: 10000010,
    products: ["Galaxy S", "Galaxy Note", "Samsung TV"],
    businessScope: ["国际"],
    location: "Seoul",
  },
  {
    name: "Sony Group Corporation",
    id: 10000011,
    products: ["PlayStation", "Xperia", "Sony Music"],
    businessScope: ["国际"],
    location: "Tokyo",
  },
  {
    name: "JPMorgan Chase & Co",
    id: 10000012,
    products: ["Banking", "Investment", "Credit Cards"],
    businessScope: ["国际"],
    location: "New York",
  },
  {
    name: "Berkshire Hathaway Inc",
    id: 10000013,
    products: ["Insurance", "Railroads", "Utilities"],
    businessScope: ["国内"],
    location: "Omaha",
  },
  {
    name: "Exxon Mobil Corporation",
    id: 10000014,
    products: ["Crude Oil", "Natural Gas", "Petrochemicals"],
    businessScope: ["国际"],
    location: "Irving",
  },
  {
    name: "Johnson & Johnson",
    id: 10000015,
    products: ["Pharmaceuticals", "Medical Devices", "Consumer Health"],
    businessScope: ["国际", "国内"],
    location: "New Brunswick",
  },
  {
    name: "Procter & Gamble Company",
    id: 10000016,
    products: ["Beauty", "Health", "Household"],
    businessScope: ["国际"],
    location: "Cincinnati",
  },
  {
    name: "BHP Group Limited",
    id: 10000017,
    products: ["Iron Ore", "Copper", "Coal"],
    businessScope: ["国际"],
    location: "Melbourne",
  },
  {
    name: "Volkswagen AG",
    id: 10000018,
    products: ["Volkswagen", "Audi", "Porsche"],
    businessScope: ["国际"],
    location: "Wolfsburg",
  },
  {
    name: "Toyota Motor Corporation",
    id: 10000019,
    products: ["Toyota", "Lexus", "Hilux"],
    businessScope: ["国际"],
    location: "Toyota City",
  },
  {
    name: "Nestlé S.A.",
    id: 10000020,
    products: ["Food", "Beverages", "Nutrition"],
    businessScope: ["国际"],
    location: "Vevey",
  },
];

export {companies}